import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Comics.module.css'
import ComicsIndex from '../components/ComicsIndex';


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <script src="https://kit.fontawesome.com/867df664d5.js" crossOrigin="anonymous" defer></script>
      </Head>
      <main className={styles.main}>
        <ComicsIndex></ComicsIndex>
      </main>
    </>
  )
}
