import Head from 'next/head'
import { Inter } from '@next/font/google'
import { Header } from '@/components/Header/Header';
import { Hero } from '@/components/Hero/Hero';
import ComicsIndex from '../components/ComicIndex/ComicIndex';
import { Favorites } from '../components/Favorites/Favorites';
import { Footer } from '@/components/Footer/Footer';
import AppContextProvider  from "../state/AppContext";
import styles from '../styles/IndexPage.module.css';
import "@fortawesome/fontawesome-svg-core/styles.css";
import {
	faBolt,
  faBoltLightning,
	faFilter,
	faTimes,
	faAngleLeft,
	faAngleRight,
	faBars,
	faAngleDown,
} from "@fortawesome/free-solid-svg-icons";
// Using this syntax, because error is caused using other syntax for whatever reason
const { library, config } = require("@fortawesome/fontawesome-svg-core");

config.autoAddCss = false;
library.add(
	faBolt,
  faBoltLightning,
	faFilter,
	faTimes,
	faAngleLeft,
	faAngleRight,
	faBars,
	faAngleDown
);

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Comic Closet</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <script src="https://kit.fontawesome.com/867df664d5.js" crossOrigin="anonymous" defer></script>
      </Head>
      <AppContextProvider>
          <Header/>
          <Hero/>
          <main className={styles.comicsContent}>
            <ComicsIndex></ComicsIndex>
            <div className={styles.comicsHideMobile}>
              <Favorites/>
            </div>
          </main>
        <Footer/>
      </AppContextProvider>
    </>
  )
}
